Repository VerifyTests/DiffEngine, pull requests merged in 2020-09, with the labels that each got.

#72 Add options to tray tool
  src/DiffEngineTray.Tests/MenuBuilderTest.Empty.verified.png
  src/DiffEngineTray.Tests/MenuBuilderTest.Full.verified.png
  src/DiffEngineTray.Tests/MenuBuilderTest.OnlyDelete.verified.png
  src/DiffEngineTray.Tests/MenuBuilderTest.OnlyMove.verified.png
  src/DiffEngineTray.Tests/MenuBuilderTest.cs
  src/DiffEngineTray.Tests/OptionsFormTests.Default.verified.png
  src/DiffEngineTray.Tests/OptionsFormTests.WithKeys.verified.png
  src/DiffEngineTray.Tests/OptionsFormTests.cs
  src/DiffEngineTray.Tests/SettingsHelperTests.ReadWrite.verified.txt
  src/DiffEngineTray.Tests/SettingsHelperTests.cs
  src/DiffEngineTray/AsyncTimer.cs
  src/DiffEngineTray/Extensions.cs
  src/DiffEngineTray/HotKey/KeyModifiers.cs
  src/DiffEngineTray/HotKey/KeyRegister.cs
  src/DiffEngineTray/MenuBuilder.cs
  src/DiffEngineTray/Program.cs
  src/DiffEngineTray/Settings/HotKey.cs
  src/DiffEngineTray/Settings/KeyBindingIds.cs
  src/DiffEngineTray/Settings/OptionsForm.Designer.cs
  src/DiffEngineTray/Settings/OptionsForm.cs
  src/DiffEngineTray/Settings/OptionsForm.resx
  src/DiffEngineTray/Settings/OptionsFormLauncher.cs
  src/DiffEngineTray/Settings/Settings.cs
  src/DiffEngineTray/Settings/SettingsHelper.cs
  src/DiffEngineTray/Settings/SettingsValidator.cs
  src/appveyor.yml
Labels: Feature

#86 Correct casing on AzureDevops detection
  src/DiffEngine/BuildServerDetector.cs
Labels: Bug

#95 Add sync API
  docs/diff-tool.custom.md
  readme.md
  src/DiffEngine.Tests/DiffRunnerTests.cs
  src/DiffEngine.Tests/DiffToolsTest.cs
  src/DiffEngine/DiffRunner.cs
  src/DiffEngine/DiffRunner_Kill.cs
  src/DiffEngine/DisabledChecker.cs
  src/DiffEngine/MaxInstance.cs
  src/DiffEngine/ResolvedTool.cs
  src/DiffEngine/Tray/DiffEngineTray.cs
  src/DiffEngineTray.Tests/OptionsFormTests.Default.verified.png
  src/DiffEngineTray.Tests/OptionsFormTests.WithKeys.verified.png
  src/DiffEngineTray.Tests/PiperTest.cs
  src/DiffEngineTray/PiperClient.cs
  src/Directory.Build.props
Labels: Improvement
